
export const LOAD_SCREENS = "LOAD_SCREENS";
export const UPDATE_HAS_REACHED_SUMMARY = "UPDATE_HAS_REACHED_SUMMARY"
export const UPDATE_CURRENT_SCREEN = "UPDATE_CURRENT_SCREEN"
export const MOVE_SCREEN_FORWARD = "MOVE_SCREEN_FORWARD"
export const MOVE_SCREEN_BACKWARD = "MOVE_SCREEN_BACKWARD"

