export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_EMAIL_ERROR = "UPDATE_EMAIL_ERROR";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD"
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR"
export const UPDATE_FIRSTNAME = "UPDATE_FIRSTNAME"
export const UPDATE_FIRSTNAME_ERROR = "UPDATE_FIRSTNAME_ERROR"
export const UPDATE_LASTNAME = "UPDATE_LASTNAME"
export const UPDATE_LASTNAME_ERROR = "UPDATE_LASTNAME_ERROR"
