
import { blue, deepPurple, pink, green, orange, red } from '@material-ui/core/colors';

const WHITE_COL = '#FFFFFF'
const BLACK_COL = '#000000'

const PRIMARY_PALETTE = { MAIN: { COL: blue[500], TEXT: BLACK_COL }, LIGHT: { COL: '#66E0FF', TEXT: BLACK_COL  }, DARK: { COL: '#007EA2', TEXT: WHITE_COL } }
const SECONDARY_PALETTE = { MAIN: { COL: deepPurple[500], TEXT: WHITE_COL }, LIGHT: { COL: '#A07ECF', TEXT: BLACK_COL  }, DARK: { COL: '#42276F', TEXT: WHITE_COL } }
const ERROR_PALETTE = { MAIN: { COL: red[500], TEXT: BLACK_COL }, LIGHT: { COL: '#FF6951', TEXT: BLACK_COL  }, DARK: { COL: '#AD0000', TEXT: WHITE_COL } }
const WARNING_PALETTE = { MAIN: { COL: orange[500], TEXT: BLACK_COL }, LIGHT: { COL: '#FFB141', TEXT: BLACK_COL  }, DARK: { COL: '#A85400', TEXT: WHITE_COL } }
const SUCCESS_PALETTE = { MAIN: { COL: green[500], TEXT: WHITE_COL }, LIGHT: { COL: '#60B95C', TEXT: BLACK_COL  }, DARK: { COL: '#005A00', TEXT: WHITE_COL } }


export default {
  WHITE: WHITE_COL,
  BLACK: BLACK_COL,
  BLUE: '#18819D',
  GREEN: '#2B882F',
  PURPLE: '#624983',
  PINK: '#E70572',
  GREY: '#636E72',
  MATERIAL: {
    GREY: 'rgba(0, 0, 0, 0.54)'
  },
  VIRIDIS: {
    SCALE1: { BG: '#430154', TEXT: WHITE_COL },
    SCALE2: { BG: '#482878', TEXT: WHITE_COL },
    SCALE3: { BG: '#3E4A89', TEXT: WHITE_COL },
    SCALE4: { BG: '#2C5C81', TEXT: WHITE_COL },
    SCALE5: { BG: '#30A6B5', TEXT: WHITE_COL },
    SCALE6: { BG: '#22AA94', TEXT: BLACK_COL },
    SCALE7: { BG: '#35B778', TEXT: BLACK_COL },
    SCALE8: { BG: '#6CCD59', TEXT: BLACK_COL },
    SCALE9: { BG: '#B4DE2C', TEXT: BLACK_COL },
    SCALE10: { BG: '#FDE725', TEXT: BLACK_COL },
  },
  THEME: {
    PRIMARY: { ...PRIMARY_PALETTE },
    SECONDARY: { ...SECONDARY_PALETTE },
    ERROR: { ...ERROR_PALETTE },
    WARNING: { ...WARNING_PALETTE },
    INFO: { ...PRIMARY_PALETTE },
    SUCCESS: { ...SUCCESS_PALETTE },
  }
}